// SYSTEM — alerts, model performance, system status, data sources,
// digital thread, query console, audit log.
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { get, post, apiBase } from '../services/api';
import { useSystem } from '../components/SystemContext';
import { Panel, PageHeader, StatusTag, StateTag, LoadingState, ErrorState, EmptyState, Metric, MetricGrid, NotAvailable, Segmented, SearchInput, KV } from '../components/ui';
import { int, istDateTime, istTime, num, pctOf } from '../lib/format';
import { Icon } from '../components/icons';
import { useAuth } from '../context/AuthContext';

/* ================= ALERTS ================= */
export function Alerts() {
  const sys = useSystem();
  const nav = useNavigate();
  const [rows, setRows] = useState<any[] | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [sev, setSev] = useState('ALL');

  useEffect(() => {
    let alive = true;
    get('/api/alerts').then((r) => { if (alive) { setRows(r); sys.markUpdated(); } })
      .catch((e) => { if (alive) setErr(String(e?.message || e)); });
    return () => { alive = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sys.refreshKey]);

  if (err) return <ErrorState title="ALERT SERVICE UNAVAILABLE" message="Unable to retrieve active alerts." detail={err} onRetry={() => sys.bumpRefresh()} />;
  if (!rows) return <LoadingState label="FETCHING ACTIVE ALERTS" />;

  const counts: Record<string, number> = {
    ALL: rows.length,
    Critical: rows.filter((r) => r.severity === 'Critical').length,
    Warning: rows.filter((r) => r.severity === 'Warning').length,
  };
  rows.forEach((r) => { if (counts[r.severity] == null) counts[r.severity] = 1; });
  const filtered = sev === 'ALL' ? rows : rows.filter((r) => r.severity === sev);

  return (
    <div>
      <PageHeader
        title="ALERT CENTER"
        sub="Active operational alerts generated by the prediction pipeline and threshold rules, ordered by severity."
        provenance="LIVE DETECTION · SYNTHETIC DATA"
      >
        <Segmented value={sev} onChange={setSev} ariaLabel="Severity filter"
          options={Object.entries(counts).map(([k, v]) => ({ id: k, label: k.toUpperCase(), count: v }))} />
      </PageHeader>

      <Panel title="ACTIVE ALERTS" sub={`${filtered.length} ALERTS`} icon="alert" bodyClass="p-0">
        {filtered.length === 0 ? (
          <div className="p-3"><EmptyState title="NO ACTIVE ALERTS" message="No aircraft currently require immediate attention." hint={`LAST CHECK ${istTime(new Date().toISOString())}`} /></div>
        ) : (
          <div className="overflow-x-auto">
            <table className="dt">
              <thead><tr><th>TIME</th><th>SEVERITY</th><th>TYPE</th><th>AIRCRAFT</th><th>COMPONENT</th><th>MESSAGE</th><th>REQUIRED ACTION</th><th>STATUS</th><th></th></tr></thead>
              <tbody>
                {filtered.map((a, i) => (
                  <tr key={i}>
                    <td className="mono">{istTime(a.timestamp)}</td>
                    <td><StatusTag s={a.severity === 'Critical' ? 'Critical' : a.severity === 'Warning' ? 'High' : 'Low'} label={a.severity === 'Critical' ? 'CRITICAL' : a.severity === 'Warning' ? 'WARNING' : a.severity.toUpperCase()} /></td>
                    <td>{a.type}</td>
                    <td className="mono">{a.aircraft_id || '—'}</td>
                    <td>{a.component || '—'}</td>
                    <td style={{ whiteSpace: 'normal' }} className="max-w-[320px]">{a.message}</td>
                    <td style={{ whiteSpace: 'normal' }} className="max-w-[240px] text-[11.5px]">{a.action}</td>
                    <td><StatusTag s={a.status} /></td>
                    <td>
                      {a.aircraft_id && (
                        <button className="btn btn-xs" onClick={() => nav(`/app/aircraft/${a.aircraft_id}/diagnostics`)}>DIAGNOSTICS →</button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </div>
  );
}

/* ================= MODEL PERFORMANCE ================= */
export function Models() {
  const sys = useSystem();
  const [rows, setRows] = useState<any[] | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [target, setTarget] = useState('failure');
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = () => get('/api/models');
  useEffect(() => {
    let alive = true;
    load().then((r) => { if (alive) { setRows(r); sys.markUpdated(); } })
      .catch((e) => { if (alive) setErr(String(e?.message || e)); });
    return () => { alive = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sys.refreshKey]);

  if (err) return <ErrorState title="MODEL REGISTRY UNAVAILABLE" message="Unable to retrieve the model registry." detail={err} onRetry={() => sys.bumpRefresh()} />;
  if (!rows) return <LoadingState label="FETCHING MODEL REGISTRY" />;

  const train = async () => {
    setBusy(true);
    try {
      const r = await post('/api/models/train', { target, kind: target === 'rul' ? 'regression' : target });
      setNotice(`MODEL ${r.version} TRAINED ON SYNTHETIC DATA — DEMO EVALUATION METICS ONLY`);
      setRows(await load());
    } catch (e: any) { setNotice(`TRAINING FAILED — ${String(e?.message || e).slice(0, 120)}`); }
    setBusy(false);
  };

  const fmtMetric = (k: string, v: any) => {
    if (typeof v !== 'number') return String(v);
    if (['f1', 'precision', 'recall', 'contamination'].includes(k)) return num(v, 3);
    return num(v, 1);
  };

  return (
    <div>
      <PageHeader
        title="MODEL PERFORMANCE"
        sub="Registered model versions with their recorded evaluation metrics. Metrics are demo evaluations on synthetic data — not real-world performance."
        provenance="REGISTRY · DEMO EVALUATION ON SYNTHETIC DATA"
      />

      {notice && <div className="mb-3 border border-line-strong bg-surface2 px-3 py-2 font-mono text-[10.5px] uppercase tracking-[0.06em] text-acc">{notice}</div>}

      <div className="grid gap-3">
        {rows.map((m, i) => (
          <Panel key={i} title={`${m.name.toUpperCase()} — ${m.version}`} sub={m.purpose} icon="chip"
            right={<StateTag st={m.status === 'Active' ? 'ok' : 'off'} label={m.status.toUpperCase()} />}>
            <div className="grid gap-x-8 gap-y-2 sm:grid-cols-2 lg:grid-cols-4">
              <div>
                <div className="tlabel mb-1">EVALUATION METRICS</div>
                {Object.entries(m.metrics || {}).filter(([k]) => k !== 'note').map(([k, v]) => (
                  <KV key={k} k={k.replace(/_/g, ' ')} v={fmtMetric(k, v)} />
                ))}
                {Object.keys(m.metrics || {}).filter((k) => k !== 'note').length === 0 && <NotAvailable />}
              </div>
              <div>
                <div className="tlabel mb-1">REGISTRATION</div>
                <KV k="VERSION" v={m.version} />
                <KV k="STATUS" v={m.status.toUpperCase()} />
                <KV k="LAST TRAINED" v={istDateTime(m.trained)} />
              </div>
              <div className="lg:col-span-2">
                <div className="tlabel mb-1">NOT AVAILABLE IN REGISTRY</div>
                <div className="font-mono text-[10px] leading-relaxed text-txt-faint">
                  CONFUSION MATRIX · TRAINING DATA VOLUME · PREDICTION COUNT — NOT RECORDED BY THE PROTOTYPE REGISTRY.
                  FEATURE CONTRIBUTIONS ARE COMPUTED PER PREDICTION (SEE DIAGNOSTICS), NOT STORED AS GLOBAL IMPORTANCE.
                </div>
                {m.metrics?.note && <div className="mt-2 border border-[#2a2312] bg-warn-dim px-2 py-1 font-mono text-[9px] uppercase tracking-[0.06em] text-warn">{m.metrics.note}</div>}
              </div>
            </div>
          </Panel>
        ))}

        <Panel title="TRAINING — DEMO" sub="RETRAINS THE PIPELINE ON SYNTHETIC DATA" icon="gear">
          <div className="flex flex-wrap items-center gap-2">
            <select className="inp max-w-xs" value={target} onChange={(e) => setTarget(e.target.value)} aria-label="Training target">
              <option value="failure">CLASSIFICATION — FAILURE</option>
              <option value="rul">REGRESSION — RUL</option>
              <option value="anomaly">ANOMALY DETECTION</option>
            </select>
            <button className="btn btn-primary" onClick={train} disabled={busy}><Icon name="refresh" size={12} /> {busy ? 'TRAINING…' : 'TRAIN MODEL'}</button>
            <span className="font-mono text-[9.5px] leading-relaxed tracking-[0.05em] text-txt-faint">
              TRAINS ON THE SEEDED SYNTHETIC DATASET · RECORDED METRICS ARE DEMO EVALUATIONS ONLY.
            </span>
          </div>
        </Panel>
      </div>
    </div>
  );
}

/* ================= SYSTEM STATUS ================= */
export function SystemStatus() {
  const sys = useSystem();
  const { user } = useAuth();
  const [health, setHealth] = useState<any[] | null>(null);
  const [dq, setDq] = useState<any>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const [h, q] = await Promise.all([get('/api/system-health'), get('/api/data-quality')]);
        if (!alive) return;
        setHealth(h); setDq(q); sys.markUpdated();
      } catch (e: any) { if (alive) setErr(String(e?.message || e)); }
    })();
    return () => { alive = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sys.refreshKey]);

  if (err) return <ErrorState title="SYSTEM STATUS UNAVAILABLE" message="Unable to retrieve service status." detail={err} onRetry={() => sys.bumpRefresh()} />;
  if (!health || !dq) return <LoadingState label="CHECKING SYSTEM STATUS" />;

  const services = [
    ...health,
    { service: 'Data Ingestion', status: 'Operational' },
  ];

  return (
    <div>
      <PageHeader
        title="SYSTEM STATUS"
        sub="Backend services, data-quality indicators and environment information for this deployment."
        provenance="ENVIRONMENT: DEMO · DATABASE: SQLITE/POSTGRES PER DEPLOYMENT"
      />

      <div className="grid gap-3">
        <Panel title="SERVICES" sub="BACKEND COMPONENT STATUS" icon="database" bodyClass="p-0">
          <table className="dt">
            <thead><tr><th>SERVICE</th><th>STATUS</th><th>DESCRIPTION</th></tr></thead>
            <tbody>
              {services.map((s, i) => (
                <tr key={i}>
                  <td className="text-txt">{s.service}</td>
                  <td><StateTag st={s.status === 'Operational' ? 'ok' : 'crit'} label={s.status.toUpperCase()} /></td>
                  <td style={{ whiteSpace: 'normal' }} className="text-[11.5px]">{
                    ({ API: 'FastAPI application serving the operational data model', Database: 'Relational store — aircraft, telemetry, work orders, records', 'ML Service': 'Inference pipeline — classifier, regressor, anomaly detector', 'Data Ingestion': 'Telemetry ingestion and CSV upload processing', 'Model Service': 'Model registry and training jobs' } as Record<string, string>)[s.service] || '—'
                  }</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Panel>

        <Panel title="DATA QUALITY" sub="TELEMETRY PIPELINE INDICATORS" icon="chart">
          <MetricGrid cols="grid-cols-2 lg:grid-cols-4">
            <Metric label="TELEMETRY COMPLETENESS" value={pctOf(dq.telemetry_completeness, 1)} st={dq.telemetry_completeness >= 95 ? 'ok' : 'warn'} />
            <Metric label="SENSOR RELIABILITY" value={pctOf(dq.sensor_reliability, 1)} st={dq.sensor_reliability >= 80 ? 'ok' : 'warn'} hint="RANGE-VALIDATED READINGS" />
            <Metric label="RECORD COMPLETENESS" value={pctOf(dq.record_completeness, 1)} st={dq.record_completeness >= 95 ? 'ok' : 'warn'} />
            <Metric label="OVERALL SCORE" value={pctOf(dq.score, 1)} st={dq.score >= 80 ? 'ok' : 'warn'} hint="WEIGHTED COMPOSITE" />
          </MetricGrid>
          <div className="mt-3 overflow-x-auto border-t border-line pt-2">
            <table className="dt">
              <thead><tr><th>READINGS</th><th>MISSING FIELDS</th><th>STALE FEEDS (&gt;24H)</th></tr></thead>
              <tbody>
                <tr>
                  <td className="mono">{int(dq.readings)}</td>
                  <td className="mono">{pctOf(dq.missing_pct, 1)}</td>
                  <td className="mono">{int(dq.stale_feeds)}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Panel>

        <div className="grid gap-3 lg:grid-cols-2">
          <Panel title="ENVIRONMENT" icon="gear">
            <KV k="APPLICATION" v="AEROSENTINEL — PROTOTYPE" />
            <KV k="API BASE" v={<span className="break-all">{apiBase || 'SAME ORIGIN'}</span>} />
            <KV k="OPERATOR" v={`${user?.username || '—'} / ${String(user?.role || '').toUpperCase()}`} />
            <KV k="ACTIVE MODEL" v={sys.modelName} />
            <KV k="LAST UPDATED" v={sys.lastUpdated ? istTime(sys.lastUpdated.toISOString()) : '—'} />
            <KV k="DATA MODE" v={sys.simActive ? 'LIVE SIMULATION' : 'SIMULATION'} vClass="text-warn" />
          </Panel>

          <Panel title="SYSTEM ARCHITECTURE" sub="PROTOTYPE STACK" icon="database">
            <div className="space-y-2">
              {[
                ['DATA LAYER', 'Synthetic sensors · maintenance records · inventory · flight records'],
                ['PROCESSING', 'Ingestion · validation · feature engineering'],
                ['ML PIPELINE', 'IsolationForest anomaly · RandomForest failure classifier · RUL regressor'],
                ['APPLICATION', 'FastAPI · React operations console'],
                ['DECISION SUPPORT', 'Alerts · recommendations · scheduling — human approval mandatory'],
              ].map(([t, d]) => (
                <div key={t} className="grid grid-cols-[140px_1fr] gap-3 border-b border-line/60 pb-1.5 last:border-0">
                  <span className="tlabel pt-0.5">{t}</span>
                  <span className="text-[11.5px] leading-snug text-txt-dim">{d}</span>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      </div>
    </div>
  );
}

/* ================= DATA SOURCES ================= */
export function DataSources() {
  const [res, setRes] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const send = async (f: File) => {
    setBusy(true); setErr(null); setRes(null);
    try {
      const fd = new FormData(); fd.append('file', f);
      const r = await fetch(apiBase + '/api/data/upload', {
        method: 'POST', body: fd,
        headers: { 'X-Role': localStorage.getItem('role') || 'command' },
      });
      if (!r.ok) throw new Error(`UPLOAD FAILED — API ${r.status}`);
      setRes(await r.json());
    } catch (e: any) { setErr(String(e?.message || e)); }
    setBusy(false);
  };

  return (
    <div>
      <PageHeader
        title="DATA SOURCES"
        sub="Telemetry ingestion for the prototype pipeline. All operational data in this deployment is synthetic; uploads are validated and profiled, not persisted to the operational model."
        provenance="DEMO INGESTION · SYNTHETIC DATA ONLY"
      />

      <div className="grid gap-3 lg:grid-cols-[minmax(0,3fr)_minmax(340px,1fr)]">
        <Panel title="CSV INGESTION" sub="VALIDATION + PROFILE" icon="file">
          <label className="flex cursor-pointer flex-col items-center justify-center border border-dashed border-line-strong bg-inset/50 px-6 py-10 text-center">
            <Icon name="file" size={18} className="mb-2 text-txt-faint" />
            <span className="font-mono text-[11px] uppercase tracking-[0.1em] text-txt-dim">
              {busy ? 'PROCESSING UPLOAD…' : 'SELECT TELEMETRY CSV'}
            </span>
            <span className="mt-1 font-mono text-[9.5px] text-txt-faint">COLUMNS: AIRCRAFT_ID · COMPONENT · TEMPERATURE · PRESSURE · VIBRATION · RPM · …</span>
            <input type="file" accept=".csv" className="sr-only" onChange={(e) => e.target.files && send(e.target.files[0])} disabled={busy} />
          </label>

          {err && <div className="mt-3"><ErrorState title="INGESTION ERROR" message={err} onRetry={() => setErr(null)} /></div>}

          {res && (
            <div className="mt-3">
              <div className="tlabel tlabel-dim mb-1.5">INGESTION PROFILE</div>
              <KV k="FILE" v={res.file} />
              <KV k="ROWS" v={int(res.rows)} />
              <KV k="COLUMNS" v={String(res.columns?.length ?? 0)} />
              <KV k="MISSING VALUES" v={int(res.missing)} />
              <KV k="VALIDATION" v={<StateTag st={res.status === 'Valid' ? 'ok' : 'warn'} label={String(res.status).toUpperCase()} />} />
              <KV k="QUALITY SCORE" v={pctOf(res.quality, 1)} />
              <div className="mt-2 border border-line bg-inset px-2 py-1.5 font-mono text-[9.5px] leading-relaxed text-txt-faint">
                DETECTED COLUMNS: {(res.columns || []).join(' · ').toUpperCase() || '—'}
              </div>
            </div>
          )}
        </Panel>

        <Panel title="SOURCE REGISTERS" sub="WHAT FEEDS THIS DEPLOYMENT" icon="database">
          <div className="space-y-3">
            {[
              ['TELEMETRY', 'Synthetic sensor stream generated per aircraft and component. Degradation scenarios are injected via the simulation controls.'],
              ['MAINTENANCE RECORDS', 'Seeded synthetic history — scheduled, unscheduled, inspection and overhaul events.'],
              ['INVENTORY', 'Synthetic spare-parts register with stock, demand and lead times.'],
              ['MODEL OUTPUTS', 'Computed live by the in-process ML pipeline (classifier, regressor, anomaly detector).'],
            ].map(([t, d]) => (
              <div key={t} className="border-b border-line/60 pb-2 last:border-0">
                <div className="tlabel tlabel-dim">{t}</div>
                <div className="mt-0.5 text-[11.5px] leading-relaxed text-txt-dim">{d}</div>
              </div>
            ))}
            <a className="btn" href={apiBase + '/api/data/sample'}><Icon name="download" size={12} /> DOWNLOAD SAMPLE CSV</a>
          </div>
        </Panel>
      </div>
    </div>
  );
}

/* ================= AUDIT LOG ================= */
const AUDIT_CATEGORY: Record<string, string> = {
  login: 'AUTH', work_order_approved: 'WORK ORDER', work_order_detected: 'WORK ORDER',
  work_order_scheduled: 'WORK ORDER', work_order_in_progress: 'WORK ORDER',
  work_order_completed: 'WORK ORDER', work_order_cancelled: 'WORK ORDER',
  simulate_degradation: 'SIMULATION', model_trained: 'MODEL', dataset_uploaded: 'DATA',
};

export function AuditLog() {
  const sys = useSystem();
  const [rows, setRows] = useState<any[] | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [q, setQ] = useState('');

  useEffect(() => {
    let alive = true;
    get('/api/audit').then((r) => { if (alive) { setRows(r); sys.markUpdated(); } })
      .catch((e) => { if (alive) setErr(String(e?.message || e)); });
    return () => { alive = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sys.refreshKey]);

  if (err) return <ErrorState title="AUDIT LOG UNAVAILABLE" message="Unable to retrieve the audit trail." detail={err} onRetry={() => sys.bumpRefresh()} />;
  if (!rows) return <LoadingState label="FETCHING AUDIT TRAIL" />;

  const filtered = rows.filter((r) => !q ||
    (r.actor || '').toLowerCase().includes(q.toLowerCase()) ||
    (r.action || '').toLowerCase().includes(q.toLowerCase()) ||
    (r.detail || '').toLowerCase().includes(q.toLowerCase()));

  return (
    <div>
      <PageHeader
        title="AUDIT LOG"
        sub="Chronological record of operator and system actions: logins, work-order approvals, simulation events, training jobs and data uploads."
        provenance="AUDIT TRAIL · PROTOTYPE"
      >
        <SearchInput value={q} onChange={setQ} placeholder="SEARCH ACTOR / ACTION" />
        <button className="btn" onClick={() => sys.bumpRefresh()}><Icon name="refresh" size={12} /> REFRESH</button>
      </PageHeader>

      <Panel title="EVENT TRAIL" sub={`${filtered.length} ENTRIES · NEWEST FIRST`} icon="clock" bodyClass="p-0">
        {filtered.length === 0 ? (
          <div className="p-3"><EmptyState title="NO AUDIT ENTRIES YET" message="Actions such as logins, work-order approvals and simulation events are recorded here as they occur." hint={`LAST FETCH ${istTime(new Date().toISOString())}`} /></div>
        ) : (
          <div className="overflow-x-auto">
            <table className="dt">
              <thead><tr><th>TIME</th><th>CATEGORY</th><th>ACTOR</th><th>ACTION</th><th>DETAIL</th></tr></thead>
              <tbody>
                {filtered.map((r, i) => (
                  <tr key={i}>
                    <td className="mono">{istTime(r.t)}</td>
                    <td><span className="font-mono text-[10px] uppercase tracking-[0.08em] text-acc">{AUDIT_CATEGORY[r.action] || 'SYSTEM'}</span></td>
                    <td className="mono">{r.actor}</td>
                    <td className="mono text-txt">{(r.action || '').replace(/_/g, ' ').toUpperCase()}</td>
                    <td style={{ whiteSpace: 'normal' }} className="max-w-[420px]">{r.detail || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </div>
  );
}

/* ================= QUERY CONSOLE (copilot) ================= */
export function Copilot() {
  const [q, setQ] = useState('Why is AS-014 high risk?');
  const [a, setA] = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const ask = async (query?: string) => {
    const question = query ?? q;
    if (query) setQ(query);
    setBusy(true); setErr(null); setA('');
    try {
      const r = await get('/api/copilot?q=' + encodeURIComponent(question));
      setA(r.answer);
    } catch (e: any) { setErr(String(e?.message || e)); }
    setBusy(false);
  };

  useEffect(() => { ask(); /* eslint-disable-next-line */ }, []);

  const SAMPLES = ['highest failure risk', 'vibration anomalies', 'spare parts critical', 'tasks due this week', 'summarize fleet health'];

  return (
    <div>
      <PageHeader
        title="QUERY CONSOLE"
        sub="Retrieval-based, read-only queries answered from live application data. The console cannot issue operational commands."
        provenance="READ-ONLY · RETRIEVAL FROM LIVE DATA"
      />

      <div className="grid gap-3 lg:grid-cols-[minmax(0,3fr)_minmax(340px,1fr)]">
        <Panel title="QUERY" icon="search">
          <form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); ask(); }}>
            <input className="inp font-mono text-[12px]" value={q} onChange={(e) => setQ(e.target.value)} aria-label="Query" />
            <button className="btn btn-primary" type="submit" disabled={busy}>{busy ? 'QUERYING…' : 'ASK'}</button>
          </form>
          {err && <div className="mt-3"><ErrorState title="QUERY FAILED" message="The query service could not be reached." detail={err} onRetry={() => ask()} /></div>}
          <div className="mt-3">
            <div className="tlabel tlabel-dim mb-1.5">RESPONSE</div>
            {busy ? <div className="font-mono text-[11px] uppercase tracking-[0.1em] text-txt-faint">RETRIEVING…</div> :
              a ? <div className="whitespace-pre-wrap border border-line bg-inset p-3 font-mono text-[12px] leading-relaxed text-txt-dim">{a}</div>
                : <NotAvailable label="NO RESPONSE" />}
          </div>
        </Panel>

        <Panel title="SAMPLE QUERIES" sub="SUPPORTED BY THE RETRIEVER" icon="clipboard">
          <div className="grid gap-1.5">
            {SAMPLES.map((s) => (
              <button key={s} className="btn justify-start" onClick={() => ask(s)}>{s}</button>
            ))}
            <button className="btn justify-start" onClick={() => ask('Why is AS-014 high risk?')}>why is AS-014 high risk?</button>
          </div>
          <div className="mt-3 border-t border-line pt-2 font-mono text-[9px] leading-relaxed tracking-[0.05em] text-txt-faint">
            ANSWERS ARE COMPUTED FROM THE LIVE SYNTHETIC DATASET. THE CONSOLE IS READ-ONLY AND CANNOT CREATE, MODIFY OR AUTHORIZE ANYTHING.
          </div>
        </Panel>
      </div>
    </div>
  );
}

/* ================= DIGITAL THREAD ================= */
export function Thread() {
  const sys = useSystem();
  const [t, setT] = useState<any>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    let alive = true;
    get(`/api/digital-thread?aid=${sys.currentAircraft}`).then((r) => { if (alive) { setT(r); sys.markUpdated(); } })
      .catch((e) => { if (alive) setErr(String(e?.message || e)); });
    return () => { alive = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sys.refreshKey, sys.currentAircraft]);

  if (err) return <ErrorState title="DIGITAL THREAD UNAVAILABLE" message="Unable to retrieve the digital thread." detail={err} onRetry={() => sys.bumpRefresh()} />;
  if (!t) return <LoadingState label="TRACING DIGITAL THREAD" />;

  const cur = t.current;

  return (
    <div>
      <PageHeader
        title="DIGITAL THREAD"
        sub={`Sensor-to-availability pipeline for ${sys.currentAircraft}. Each stage is a live system component — the thread shows where the current prediction sits.`}
        provenance="PIPELINE VIEW · LIVE STATE"
      />

      <Panel title="PIPELINE STAGES" sub="SENSOR DATA → AIRCRAFT AVAILABILITY" icon="activity" bodyClass="p-0">
        <div className="grid grid-cols-2 divide-x divide-y divide-line border-t border-line sm:grid-cols-3 lg:grid-cols-7">
          {t.steps?.map((s: string, i: number) => {
            const active = cur && (
              (i <= 4) || (cur.failure_prob > 0.5 && i <= 8) || false
            );
            return (
              <div key={s} className={`px-3 py-2.5 ${active ? 'bg-[#14222B]' : ''}`}>
                <div className="flex items-center gap-1.5">
                  <span className={`font-mono text-[9px] ${active ? 'text-acc' : 'text-txt-faint'}`}>{String(i + 1).padStart(2, '0')}</span>
                  <span className={`font-mono text-[10px] uppercase tracking-[0.05em] ${active ? 'text-acc' : 'text-txt-dim'}`}>{s}</span>
                </div>
                {i < (t.steps?.length || 0) - 1 && <div className="mt-0.5 font-mono text-[8px] text-txt-faint">↓</div>}
              </div>
            );
          })}
        </div>
      </Panel>

      {cur ? (
        <Panel title={`LIVE EXAMPLE — ${sys.currentAircraft}`} sub={`${cur.component} · CURRENT PREDICTION`} icon="target" className="mt-3">
          <div className="grid gap-3 md:grid-cols-4">
            <Metric label="COMPONENT" value={cur.component.toUpperCase()} />
            <Metric label="FAILURE PROBABILITY" value={pctOf(cur.failure_prob * 100, 1)} st={cur.failure_prob > 0.5 ? 'crit' : 'ok'} />
            <Metric label="RUL" value={`${num(cur.rul, 1)} D`} />
            <Metric label="RECOMMENDATION" value={<span className="text-[11px] leading-snug">{cur.recommendation}</span>} />
          </div>
          <div className="mt-3 flex gap-2 border-t border-line pt-3">
            <Link className="btn" to={`/app/aircraft/${sys.currentAircraft}/diagnostics`}>OPEN DIAGNOSTICS →</Link>
            <Link className="btn btn-primary" to={`/app/work-orders?pre=${sys.currentAircraft}:${encodeURIComponent(cur.component)}`}>CREATE WORK ORDER</Link>
          </div>
        </Panel>
      ) : (
        <Panel title={`LIVE EXAMPLE — ${sys.currentAircraft}`} className="mt-3">
          <EmptyState title="NO ACTIVE PREDICTION" message="This aircraft has no elevated component risk in the current model run — the thread is in monitoring state." />
        </Panel>
      )}
    </div>
  );
}
